AWSTemplateFormatVersion: 2010-09-09
Description: Asset App's Frontend App Instance security group

Parameters:
  SGName:
    Type: String
    Default: AssetApp-Frontend-SG
  SGDescription:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  AssetAppAPISG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SGName
      GroupDescription: !Ref SGDescription
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref SGName