AWSTemplateFormatVersion: 2010-09-09
Description: Asset App's Frontend App Instance security group

Parameters:
  SGName:
    Type: String
    Default: AssetApp-API-SG
  SGDescription:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  SourceSG:
    Type: AWS::EC2::SecurityGroup::Id
  Port:
    Type: Number

Resources:
  AssetAppAPISG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SGName
      GroupDescription: !Ref SGDescription
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref Port
          ToPort: !Ref Port
          SourceSecurityGroupId: !Ref SourceSG
      Tags:
        - Key: Name
          Value: !Ref SGName