AWSTemplateFormatVersion: 2010-09-09
Description: The CI/CD pipeline for the Asset App

Parameters:
  BucketName:
    Type: String
  CodePipelineName:
    Type: String
    Default: AssetApp-CodePipeline

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Name
          Value: !Ref BucketName

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                    - "iam:PassRole"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "ec2:*"
                    - "s3:*"
                    - "cloudformation:*"
                  Resource: "*"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Policies:
          - PolicyName: "root"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "codebuild:BatchGetBuilds"
                    - "codebuild:StartBuild"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "iam:PassRole"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "ec2:*"
                    - "s3:*"
                    - "cloudformation:*"
                  Resource: "*"

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Source:
        Type: GITHUB
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref CodePipelineName
      RoleArn: !Ref CodePipelineRole
      ArtifactStore:
        Type: S3
        Location: !Ref BucketName
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Owner: ThirdParty
                Category: Source
                Version: 2
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref CodeBuild

      RestartExecutionOnUpdate: true
